/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Estructuras.ArbolAVL.ArbolAVL;
import TablaHash.T_Hash;
import TablaHash.Usuario;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author ronald
 */
public class Administrador extends javax.swing.JFrame {

    public static T_Hash tablahash;
    public static ArbolAVL arbolavl;

    /**
     * Creates new form Inicio
     */
    public Administrador() {
        initComponents();
        deshabilitarCampos();
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        tablahash = new T_Hash();
        arbolavl = new ArbolAVL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcarnet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txtcarrera = new javax.swing.JTextField();
        txtcontrasenia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JTextField();
        btncrearcategoria = new javax.swing.JButton();
        btneliminarcategoria = new javax.swing.JButton();
        btngraficaravl = new javax.swing.JButton();
        btnpreorden = new javax.swing.JButton();
        btninorden = new javax.swing.JButton();
        btnpostorden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMasivaUsuarios = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCargaMasivaLibros = new javax.swing.JMenuItem();
        jmCargaMasivaUsuarios = new javax.swing.JMenuItem();
        jmCerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmTablaHash = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel5.setText("Carrera");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel4.setText("Apellido");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel6.setText("Contraseña");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Carnet");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("USUARIOS");

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnGuardar)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btncancelar)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnModificar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                            .addComponent(btnEliminar))))
                                .addComponent(txtcontrasenia, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcarrera, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(131, 131, 131))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnNuevo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscar))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcontrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(btncancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel8.setText("Categoria");

        jLabel9.setText("Nombre");

        btncrearcategoria.setText("CREAR");
        btncrearcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearcategoriaActionPerformed(evt);
            }
        });

        btneliminarcategoria.setText("ELIMINAR");
        btneliminarcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarcategoriaActionPerformed(evt);
            }
        });

        btngraficaravl.setText("VER");
        btngraficaravl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngraficaravlActionPerformed(evt);
            }
        });

        btnpreorden.setText("PREORDEN");
        btnpreorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreordenActionPerformed(evt);
            }
        });

        btninorden.setText("INORDEN");
        btninorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninordenActionPerformed(evt);
            }
        });

        btnpostorden.setText("POSTORDEN");
        btnpostorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpostordenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(120, 120, 120))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnpreorden)
                        .addGap(18, 18, 18)
                        .addComponent(btninorden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnpostorden)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btngraficaravl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneliminarcategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncrearcategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btncrearcategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminarcategoria)
                .addGap(18, 18, 18)
                .addComponent(btngraficaravl)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpreorden)
                    .addComponent(btninorden)
                    .addComponent(btnpostorden))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        txtMasivaUsuarios.setColumns(20);
        txtMasivaUsuarios.setRows(5);
        jScrollPane1.setViewportView(txtMasivaUsuarios);

        jLabel7.setText("USUARIOS CARGADOS");

        jMenu1.setText("Archivo");

        jmCargaMasivaLibros.setText("Carga Masiva de Libros");
        jMenu1.add(jmCargaMasivaLibros);

        jmCargaMasivaUsuarios.setText("Carga Masiva de Usuarios");
        jmCargaMasivaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargaMasivaUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jmCargaMasivaUsuarios);

        jmCerrarSesion.setText("Cerrar Sesion");
        jmCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(jmCerrarSesion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Biblioteca");

        jMenuItem2.setText("Ver Libros");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        jMenuItem3.setText("Arbol AVL - Categorias");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Arbol B - LIbros");
        jMenu3.add(jMenuItem4);

        jmTablaHash.setText("Tabla Hash - Usuarios");
        jmTablaHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTablaHashActionPerformed(evt);
            }
        });
        jMenu3.add(jmTablaHash);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel7)))
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitarCampos();
        limpiarCampos();
        btnGuardar.setEnabled(true);
        btnBuscar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int carnet;
        String nombre;
        String apellido;
        String carrera;
        String contrasenia;

        if ("".equals(txtnombre.getText()) || "".equals(txtapellido.getText()) || "".equals(txtcarrera.getText()) || "".equals(txtcarnet.getText()) || "".equals(txtcontrasenia.getText())) {
            JOptionPane.showMessageDialog(null, "NO PUEDE DEJAR CAMPOS DE INFORMACION VACIOS");
        } else {
            carnet = Integer.parseInt(txtcarnet.getText());
            nombre = txtnombre.getText();
            apellido = txtapellido.getText();
            carrera = txtcarrera.getText();
            contrasenia = txtcontrasenia.getText();

            if (tablahash.insertarUsuario(carnet, nombre, apellido, carrera, contrasenia)) {
                JOptionPane.showMessageDialog(null, "USUARIO AGREGADO EXITOSAMENTE");
                limpiarCampos();
                btnGuardar.setEnabled(false);
                btnBuscar.setEnabled(true);
                deshabilitarCampos();
            } else {
                int seleccion = JOptionPane.showOptionDialog(
                        null, "Usuario ya existe. ¿Intentar de nuevo?", "Opciones", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "opcion 1");
                if (seleccion == 1) {
                    limpiarCampos();
                    btnGuardar.setEnabled(false);
                    deshabilitarCampos();
                    btnBuscar.setEnabled(true);

                }
            }
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int carnet = Integer.parseInt(txtcarnet.getText());
        Usuario usuario;
        try {
            usuario = tablahash.buscar(carnet);
            if (usuario == null) {
                JOptionPane.showMessageDialog(null, "USUARIO NO EXISTE");
            } else {
                habilitarCampos();
                txtcarnet.enable(false);
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);

                txtnombre.setText(usuario.nombre);
                txtapellido.setText(usuario.apellido);
                txtcarrera.setText(usuario.carrera);
                txtcontrasenia.setText(usuario.contrasenia);
            }
        } catch (Exception ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        limpiarCampos();
        deshabilitarCampos();
        txtcarnet.enable(true);
        btnBuscar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btncancelar.setEnabled(true);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        int carnet;
        String nombre;
        String apellido;
        String carrera;
        String contrasenia;

        if ("".equals(txtnombre.getText()) || "".equals(txtapellido.getText()) || "".equals(txtcarrera.getText()) || "".equals(txtcarnet.getText()) || "".equals(txtcontrasenia.getText())) {
            JOptionPane.showMessageDialog(null, "NO PUEDE DEJAR CAMPOS DE INFORMACION VACIOS");
        } else {
            carnet = Integer.parseInt(txtcarnet.getText());
            nombre = txtnombre.getText();
            apellido = txtapellido.getText();
            carrera = txtcarrera.getText();
            contrasenia = txtcontrasenia.getText();

            if (tablahash.editarInformacionUsuario(carnet, nombre, apellido, carrera, contrasenia)) {
                JOptionPane.showMessageDialog(null, "DATOS ACTUALIZADOS EXITOSAMENTE");
                limpiarCampos();
                btnGuardar.setEnabled(false);
                btnBuscar.setEnabled(true);
                btnModificar.setEnabled(false);
                btnEliminar.setEnabled(false);
                deshabilitarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "NO SE PUDIERON ACTUALIZAR LOS DATOS");
            }

        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int carnet;
        carnet = Integer.parseInt(txtcarnet.getText());

        if (tablahash.eliminarUsuario(carnet)) {
            JOptionPane.showMessageDialog(null, "Usuario Eliminado EXITOSAMENTE");
            limpiarCampos();
            btnGuardar.setEnabled(false);
            btnBuscar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            deshabilitarCampos();
        } else {
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jmCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCerrarSesionActionPerformed
        this.hide();
        IniciarSesion ini = new IniciarSesion();
        ini.setVisible(true);
        ini.setLocationRelativeTo(null);
        ini.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmCerrarSesionActionPerformed

    private void jmCargaMasivaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargaMasivaUsuariosActionPerformed

        //tipo de archivo a abrir
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos JSON", "json");

        // muestra el cuadro de diálogo de archivos, para que el usuario pueda elegir el archivo a abrir
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setFileFilter(filtro);
        selectorArchivos.showOpenDialog(this);
        File archivo = selectorArchivos.getSelectedFile(); // obtiene el archivo seleccionado

        if (archivo != null) {
            try {
                leerJsonUsuarios(archivo.getAbsolutePath());
            } catch (org.json.simple.parser.ParseException ex) {
                JOptionPane.showMessageDialog(null, ex + "" + "\nNo se ha encontrado el archivo", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
            } catch (InterruptedException ex) {
                Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jmCargaMasivaUsuariosActionPerformed

    private void jmTablaHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTablaHashActionPerformed
        verHash adm = new verHash();
        adm.setVisible(true);
        adm.setLocationRelativeTo(null);
        adm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);        
    }//GEN-LAST:event_jmTablaHashActionPerformed

    private void btncrearcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearcategoriaActionPerformed
        arbolavl.insertarCategoria(txtcategoria.getText());        
    }//GEN-LAST:event_btncrearcategoriaActionPerformed

    private void btneliminarcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarcategoriaActionPerformed
        arbolavl.eliminarCategoria(txtcategoria.getText());
    }//GEN-LAST:event_btneliminarcategoriaActionPerformed

    private void btngraficaravlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngraficaravlActionPerformed
        arbolavl.graficar();
    }//GEN-LAST:event_btngraficaravlActionPerformed

    private void btnpreordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreordenActionPerformed
        arbolavl.graficarPreOrden();
    }//GEN-LAST:event_btnpreordenActionPerformed

    private void btninordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninordenActionPerformed
        arbolavl.graficarInOrden();
    }//GEN-LAST:event_btninordenActionPerformed

    private void btnpostordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpostordenActionPerformed
        arbolavl.graficarPostOrden();
    }//GEN-LAST:event_btnpostordenActionPerformed

    public void leerJsonUsuarios(String archivo) throws org.json.simple.parser.ParseException, InterruptedException {
        
        txtMasivaUsuarios.setText("");
        String contenido = "";
        JSONParser parser = new JSONParser();
        try {
            Object obj = parser.parse(new FileReader(archivo));
            
            JSONObject jsonObject = (JSONObject)obj;
            //System.out.println("JSON LEIDO :" + jsonObject);
            
            JSONArray array = (JSONArray) jsonObject.get("Usuarios");
            //System.out.println("");
            for(int i = 0; i < array.size(); i++) 
            {
               JSONObject jsonObject1 =  (JSONObject)array.get(i);
                //System.out.println("DATOS DEL USUARIO: "+i);
                String carnet = jsonObject1.get("Carnet").toString();
                String nombre = jsonObject1.get("Nombre").toString();
                String apellido = jsonObject1.get("Apellido").toString();
                String carrera = jsonObject1.get("Carrera").toString();
                String contrasenia = (String) jsonObject1.get("Password");               
                
               if(tablahash.insertarUsuario(Integer.parseInt(carnet), nombre, apellido, carrera, contrasenia))               
               {
                    contenido += carnet+"-";
                    contenido += nombre+"-";
                    contenido += apellido+"-";
                    contenido += carrera+"-";                    
                    contenido += contrasenia+"\n";                 
                   
               }

                                    
            }
            txtMasivaUsuarios.setText(contenido);
           
        } catch (FileNotFoundException e) {
            //manejo de error
        } catch (IOException e) {
            //manejo de error
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    public void habilitarCampos() {
        txtnombre.enable(true);
        txtapellido.enable(true);
        txtcarrera.enable(true);
        txtcontrasenia.enable(true);
    }

    public final void deshabilitarCampos() {
        txtnombre.enable(false);
        txtapellido.enable(false);
        txtcarrera.enable(false);
        txtcontrasenia.enable(false);

    }

    public void limpiarCampos() {
        txtcarnet.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtcarrera.setText("");
        txtcontrasenia.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncrearcategoria;
    private javax.swing.JButton btneliminarcategoria;
    private javax.swing.JButton btngraficaravl;
    private javax.swing.JButton btninorden;
    private javax.swing.JButton btnpostorden;
    private javax.swing.JButton btnpreorden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmCargaMasivaLibros;
    private javax.swing.JMenuItem jmCargaMasivaUsuarios;
    private javax.swing.JMenuItem jmCerrarSesion;
    private javax.swing.JMenuItem jmTablaHash;
    private javax.swing.JTextArea txtMasivaUsuarios;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcarnet;
    private javax.swing.JTextField txtcarrera;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtcontrasenia;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}

